# numpy

Python'da bilimsel hesaplama için temel bir kütüphanedir. Yüksek performanslı çok boyutlu bir array(dizi) nesneleri ile çalışmak için içerisinde fonksiyonlar sağlar.

https://pypi.org/project/numpy/

In [1]:
#pypi
# https://pypi.org/project/numpy/
!pip install numpy


In [2]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [3]:
import numpy as np

# Array(Dizi) Oluşturma

In [4]:
# 1 boyutlu array oluşturma
a = np.array([7, 2, 9, 10])

In [5]:
a

array([ 7,  2,  9, 10])

#### type()

In [6]:
print(type(a))

<class 'numpy.ndarray'>


#### shape()

In [7]:
print(a.shape) # tuple (demet)

(4,)


In [8]:
#elamanları yazdırma
print(a[0], a[1], a[2], a[3])

7 2 9 10


In [9]:
for eleman_a in a:
    print(eleman_a)

7
2
9
10


#### elaman atama işlemi

In [10]:
a[0] = 5   

In [11]:
print(a) 

[ 5  2  9 10]


#### 2D Array

In [12]:
b = np.array([[5.2, 3.0, 4.5],[9.1, 0.1, 0.3]])

In [13]:
b

array([[5.2, 3. , 4.5],
       [9.1, 0.1, 0.3]])

In [14]:
b.shape

(2, 3)

In [15]:
print(b[0, 0], b[0, 1], b[1, 0])  #5.2    3.0   9.1

5.2 3.0 9.1


#### Elemanları yazdırma

In [16]:
for eleman in b:
    print(eleman)

[5.2 3.  4.5]
[9.1 0.1 0.3]


In [17]:
for eleman in b:
    for alt_eleman in eleman:
        print(alt_eleman)

5.2
3.0
4.5
9.1
0.1
0.3


In [18]:
for i in range(0,b.shape[0]):
    for j in range(0,b.shape[1]):
        print(b[i][j])

5.2
3.0
4.5
9.1
0.1
0.3


#### 3D Array

![numpy_array](https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png)

In [19]:
c= np.array([[[1,2],[4,3],[7,4]], [[2,5],[9,4],[7,5]], [[1,9],[3,6],[0,2]],[[9,4],[6,2],[9,8]]])

In [20]:
c

array([[[1, 2],
        [4, 3],
        [7, 4]],

       [[2, 5],
        [9, 4],
        [7, 5]],

       [[1, 9],
        [3, 6],
        [0, 2]],

       [[9, 4],
        [6, 2],
        [9, 8]]])

In [21]:
c.shape

(4, 3, 2)

In [22]:
for i in range(0,c.shape[0]):
    for j in range(c.shape[1]):
        for k in range(0,c.shape[2],1):
            print(c[i][j][k])

1
2
4
3
7
4
2
5
9
4
7
5
1
9
3
6
0
2
9
4
6
2
9
8


In [23]:
for i in range(0,c.shape[0]):
    for j in range(c.shape[1]):
        for k in range(0,c.shape[2],1):
            print(i,j,k,"elemanı: ",c[i][j][k])

0 0 0 elemanı:  1
0 0 1 elemanı:  2
0 1 0 elemanı:  4
0 1 1 elemanı:  3
0 2 0 elemanı:  7
0 2 1 elemanı:  4
1 0 0 elemanı:  2
1 0 1 elemanı:  5
1 1 0 elemanı:  9
1 1 1 elemanı:  4
1 2 0 elemanı:  7
1 2 1 elemanı:  5
2 0 0 elemanı:  1
2 0 1 elemanı:  9
2 1 0 elemanı:  3
2 1 1 elemanı:  6
2 2 0 elemanı:  0
2 2 1 elemanı:  2
3 0 0 elemanı:  9
3 0 1 elemanı:  4
3 1 0 elemanı:  6
3 1 1 elemanı:  2
3 2 0 elemanı:  9
3 2 1 elemanı:  8


# transpose  .T  (devriğini alma)

![transpose](https://i2.wp.com/datascienceparichay.com/wp-content/uploads/2021/07/transpose-a-numpy-array.png?fit=900%2C520&ssl=1)

In [24]:
b

array([[5.2, 3. , 4.5],
       [9.1, 0.1, 0.3]])

In [25]:
b.T

array([[5.2, 9.1],
       [3. , 0.1],
       [4.5, 0.3]])

In [26]:
d = b.T

In [27]:
b*d

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

### ones()  ve ones_like()  
    1 elemanlarından oluşan dizi oluşturmak için kullanılır.
    ones parametre olarak dizi boyutunu
    ones_like parametre olarak örnek diziyi alır

In [28]:
np.ones(14)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
e = np.ones((2,3))

In [30]:
e

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.ones_like(e.T)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### zeros()  ve zeros_like()  
    0 elemanlarından oluşan dizi oluşturmak için kullanılır.
    zeros parametre olarak dizi boyutunu
    zeros_like parametre olarak örnek diziyi alır

In [32]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
f= np.zeros((2,3,2,3))
f

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [34]:
np.zeros_like(f.T)

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

### eye()  ve idenrty()  
    diyagonal elemanları 1 olan matris oluşturur

In [35]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### data tipi \<dtype>  
       dtype=np.float64 
       dtype=np.int32

In [37]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [38]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [39]:
arr1

array([1., 2., 3.])

In [40]:
arr2

array([1, 2, 3])

In [41]:
arr1.dtype

dtype('float64')

# range

In [42]:
arr = np.arange(32)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

# reshape

In [44]:
arr.reshape(2,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [45]:
arr.reshape(2,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [46]:
arr.reshape(2,2,4,2)

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]]])

# Kırpma İşlemi

![image.png](https://www.oreilly.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages2172114.png)

In [47]:
b = np.arange(9).reshape(3,3)

In [48]:
b[:2,1:]

array([[1, 2],
       [4, 5]])

#### --------------------------------------------------


In [49]:
b[2]

array([6, 7, 8])

In [50]:
b[2,]

array([6, 7, 8])

In [51]:
b[2,:]

array([6, 7, 8])

In [52]:
b[2:3,]

array([[6, 7, 8]])

#### --------------------------------------------------


In [53]:
b[:,:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

#### --------------------------------------------------


In [54]:
b[1,:2]

array([3, 4])

In [55]:
b[1:2,:2]

array([[3, 4]])